#############################################################################
# Makefile for building: bin/Register
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Nov 30 11:43:24 2016
# Project:  Register.pro
# Template: app
# Command: /usr/local/software/qt4/bin/qmake -o Makefile Register.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -Wno-reorder -Wno-parentheses -Wno-unused-parameter -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/software/qt-4.8.6/mkspecs/linux-g++-64 -I. -I/usr/local/software/qt-4.8.6/include/QtCore -I/usr/local/software/qt-4.8.6/include/QtGui -I/usr/local/software/qt-4.8.6/include -I. -Iinclude -Itmp
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/software/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/usr/local/software/qt-4.8.6/lib -lQtGui -Wl,-rpath,/usr/local/software/qt4/lib -L/usr/local/software/qt4/lib -L/usr/X11R6/lib64 -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtCore -Wl,-rpath,/usr/local/software/qt4/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/software/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/attribute.cpp \
		src/database.cpp \
		src/manager.cpp \
		src/menu.cpp \
		src/readwrite.cpp \
		src/record.cpp \
		src/register.cpp 
OBJECTS       = obj/attribute.o \
		obj/database.o \
		obj/manager.o \
		obj/menu.o \
		obj/readwrite.o \
		obj/record.o \
		obj/register.o
DIST          = /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		Register.pro
QMAKE_TARGET  = Register
DESTDIR       = bin/
TARGET        = bin/Register

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Register.pro  /usr/local/software/qt-4.8.6/mkspecs/linux-g++-64/qmake.conf /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/software/qt-4.8.6/lib/libQtGui.prl \
		/usr/local/software/qt-4.8.6/lib/libQtCore.prl
	$(QMAKE) -o Makefile Register.pro
/usr/local/software/qt-4.8.6/mkspecs/common/unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri:
/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/release.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/software/qt-4.8.6/lib/libQtGui.prl:
/usr/local/software/qt-4.8.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Register.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/Register1.0.0 || $(MKDIR) obj/Register1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Register1.0.0/ && $(COPY_FILE) --parents include/attribute.h include/database.h include/doublylinkedlist.h include/hashtable.h include/manager.h include/menu.h include/readwrite.h include/record.h obj/Register1.0.0/ && $(COPY_FILE) --parents src/attribute.cpp src/database.cpp src/manager.cpp src/menu.cpp src/readwrite.cpp src/record.cpp src/register.cpp obj/Register1.0.0/ && (cd `dirname obj/Register1.0.0` && $(TAR) Register1.0.0.tar Register1.0.0 && $(COMPRESS) Register1.0.0.tar) && $(MOVE) `dirname obj/Register1.0.0`/Register1.0.0.tar.gz . && $(DEL_FILE) -r obj/Register1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/attribute.o: src/attribute.cpp include/attribute.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/attribute.o src/attribute.cpp

obj/database.o: src/database.cpp include/database.h \
		include/attribute.h \
		include/record.h \
		include/doublylinkedlist.h \
		include/hashtable.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/database.o src/database.cpp

obj/manager.o: src/manager.cpp include/manager.h \
		include/database.h \
		include/attribute.h \
		include/record.h \
		include/doublylinkedlist.h \
		include/hashtable.h \
		include/readwrite.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/manager.o src/manager.cpp

obj/menu.o: src/menu.cpp include/menu.h \
		include/manager.h \
		include/database.h \
		include/attribute.h \
		include/record.h \
		include/doublylinkedlist.h \
		include/hashtable.h \
		include/readwrite.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/menu.o src/menu.cpp

obj/readwrite.o: src/readwrite.cpp include/readwrite.h \
		include/record.h \
		include/attribute.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/readwrite.o src/readwrite.cpp

obj/record.o: src/record.cpp include/record.h \
		include/attribute.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/record.o src/record.cpp

obj/register.o: src/register.cpp include/menu.h \
		include/manager.h \
		include/database.h \
		include/attribute.h \
		include/record.h \
		include/doublylinkedlist.h \
		include/hashtable.h \
		include/readwrite.h
	$(CXX) -c -g $(CXXFLAGS) $(INCPATH) -o obj/register.o src/register.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

